// @vitest-environment jsdom
//
// Sprint 17 P3 T3.2 — Tree module-kind right-click forwarding.
//
// Pin: when the user right-clicks a `kind:'module'` TreeNode whose
// parent document has `sourceBswmdPath` set (i.e. the document was
// generated by the BSWMD-to-ECUC skeleton flow), the renderer must
// open the global ContextMenu with `kind: 'bswmd'` and `path` = the
// BSWMD file path that owns this module.
//
// Implementation (per Sprint 17 P3 plan §T3.2): TreeNode looks up
// the parent document's `sourceBswmdPath` from `useArxmlStore` when
// its `kind === 'module'`, then forwards the right-click directly to
// `openContextMenu` with `kind: 'bswmd'` and the BSWMD path. This
// bypasses the host's `onContextMenu` callback for module-kind
// nodes (so the host doesn't need to know about BSWMD-to-ECUC
// provenance).
//
// Test strategy:
//   1. Mock `openContextMenu` from ContextMenu module so we can spy
//      on it without mounting ContextMenuRoot.
//   2. Pre-populate the store with a project + 1 ECUC doc whose
//      `sourceBswmdPath = '/fake/Adc.arxml'`.
//   3. Mount the Tree, expand `/EAS`, right-click the module
//      treeitem.
//   4. Assert `openContextMenu` was called with
//      `{ path: '/fake/Adc.arxml', kind: 'bswmd', shortName: 'Adc.arxml' }`.

import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import type { ArxmlDocument } from '@core/arxml/types.js';

import { useArxmlStore } from '../../../store/useArxmlStore.js';
import * as contextMenuModule from '../../ContextMenu.js';
import { Tree } from '../Tree.js';
import type { ArxmlStoreApi } from '../Tree.js';

// Mock the `openContextMenu` module-level API so the test can
// assert the exact payload without mounting a real ContextMenuRoot.
vi.mock('../../ContextMenu', async () => {
  const actual = await vi.importActual<typeof contextMenuModule>('../../ContextMenu');
  return {
    ...actual,
    openContextMenu: vi.fn(),
  };
});

function makeDoc(): ArxmlDocument {
  return {
    path: '/fake/Adc.ecuc.arxml',
    version: '4.6',
    sourceBswmdPath: '/fake/Adc.arxml',
    packages: [
      {
        shortName: 'EAS',
        path: '/EAS',
        elements: [
          {
            kind: 'module',
            tagName: 'ECUC-MODULE-CONFIGURATION-VALUES',
            shortName: 'Adc',
            params: {},
            children: [],
            references: [],
          },
        ],
      },
    ],
  };
}

const docFixture = makeDoc();

const mockStore: ArxmlStoreApi = {
  getState: () => ({
    doc: docFixture,
    displayDoc: docFixture,
    filePath: null,
    selectedPath: null,
    dirtyPaths: new Set<string>(),
    activeDocumentPath: null,
    setDoc: vi.fn(),
    select: vi.fn(),
    updateParam: vi.fn(),
    expand: vi.fn(),
    collapse: vi.fn(),
    isExpanded: () => false,
    toggle: vi.fn(),
    locale: 'zh-CN' as const,
    isDirty: () => false,
  }),
  subscribe: () => () => undefined,
};

beforeEach(() => {
  // Pre-populate the store with a project + 1 ECUC doc whose
  // sourceBswmdPath = '/fake/Adc.arxml'. TreeNode reads this via
  // useArxmlStore.getState().doc to look up the BSWMD path for
  // module-kind nodes.
  useArxmlStore.setState({
    project: { schemaVersion: '1', id: 'p1', name: 'P', valueArxmlPaths: [], bswmdPaths: [] },
    projectPath: '/fake/proj.autosarcfg.json',
    documents: [docFixture],
    documentPaths: ['/fake/Adc.ecuc.arxml'],
    activeDocumentPath: '/fake/Adc.ecuc.arxml',
    doc: docFixture,
    displayDoc: docFixture,
    filePath: '/fake/Adc.ecuc.arxml',
  });
  vi.clearAllMocks();
});

afterEach(() => {
  cleanup();
  useArxmlStore.getState().clear();
  vi.clearAllMocks();
});

describe('Tree module-kind right-click (Sprint 17 P3 T3.2)', () => {
  it('right-clicking a module-kind treeitem opens context menu with kind:bswmd + sourceBswmdPath', () => {
    const onCtx = vi.fn();
    render(<Tree store={mockStore} onContextMenu={onCtx} />);

    // Expand `/EAS` so the module treeitem mounts.
    fireEvent.click(screen.getByTestId('chevron-/EAS'));

    const moduleItem = screen.getByTestId('treeitem-/EAS/Adc');
    expect(moduleItem).toBeInTheDocument();
    fireEvent.contextMenu(moduleItem, { clientX: 50, clientY: 50 });

    // TreeNode re-routes module-kind right-clicks to openContextMenu
    // with kind='bswmd' and the document's sourceBswmdPath.
    expect(contextMenuModule.openContextMenu).toHaveBeenCalledTimes(1);
    expect(contextMenuModule.openContextMenu).toHaveBeenCalledWith(
      {
        path: '/fake/Adc.arxml',
        kind: 'bswmd',
        shortName: 'Adc.arxml',
      },
      50,
      50,
    );
    // The host's onContextMenu is NOT called for module-kind nodes
    // (TreeNode bypasses it to do the re-route directly).
    expect(onCtx).not.toHaveBeenCalled();
  });
});