// AUTOSAR ARXML primitive types. All exported types are immutable data.
// Reference: AUTOSAR TPS_StandardizationTemplate (4.x).
//   https://www.autosar.org/fileadmin/standards/foundation/22-11/AUTOSAR_TPS_StandardizationTemplate.pdf

export type ArxmlVersion =
  | '4.2'
  | '4.4'
  | '4.6'
  | '4.7'
  | '5.0'
  | '00005'
  | '00006'
  | '00046'
  | '00048'
  | '00049'
  | '00050'
  | '00051';

export interface ArxmlDocument {
  /** Root file path or logical name */
  readonly path: string;
  /** Detected AUTOSAR major version */
  readonly version: ArxmlVersion;
  /** Top-level <AR-PACKAGES> children */
  readonly packages: readonly ArxmlPackage[];
  /**
   * Sprint 14 — set when this document was generated by the BSWMD-to-ECUC
   * skeleton flow (Task 8 in plan). Used by `removeBswmdWithCascade`
   * to find dependents. Manual / Open ARXML flows leave this undefined.
   */
  readonly sourceBswmdPath?: string;
}

export interface ArxmlPackage {
  readonly shortName: string;
  readonly longName?: string;
  readonly path: string;
  readonly elements: readonly ArxmlElement[];
  /**
   * Nested AR-PACKAGES — recursive package hierarchy. Present only when the
   * package contains `<AR-PACKAGES>` children (e.g. R21/R22 BSWMD + EcucValues
   * with `AUTOSAR_R2x > EcucDefs > <module>` shape). Omitted for the flat
   * single-level shape so existing 5-fixture round-trip signatures stay
   * field-equal.
   */
  readonly packages?: readonly ArxmlPackage[];
}

export type ArxmlElement = ArxmlModule | ArxmlContainer | ArxmlReference | ArxmlUnknown;

export interface ArxmlModule {
  readonly kind: 'module';
  readonly tagName: string;
  readonly shortName: string;
  readonly params: Readonly<Record<string, ParamValue>>;
  readonly children: readonly ArxmlElement[];
  readonly references: readonly string[];
}

export interface ArxmlContainer {
  readonly kind: 'container';
  readonly tagName: string;
  readonly shortName: string;
  readonly params: Readonly<Record<string, ParamValue>>;
  readonly children: readonly ArxmlElement[];
  /**
   * v1.7.1 S1 — true when this shell came from a BSWMD choice container
   * (`<ECUC-CHOICE-ORIENTED-STRUCTURE-DEF>` / `<ECUC-CHOICE-CONTAINER-DEF>`)
   * rather than a plain sub-container (`<ECUC-PARAM-CONF-CONTAINER-DEF>`).
   * The UI uses this marker to render the "please pick a branch" prompt
   * instead of treating the shell as an editable plain container. Omitted
   * for plain sub-container shells (use `=== undefined`, not `=== false`).
   */
  readonly isChoiceContainer?: boolean;
  /**
   * v1.7.1 S1 — shortNames of the alternative branches the user can pick
   * from. Set only when `isChoiceContainer` is true; preserves iteration
   * order of `ContainerDef.choices` (which the BSWMD parser emits in
   * source order, so the UI picker renders branches in the same order).
   */
  readonly choiceBranches?: readonly string[];
  /**
   * v1.7.1 S3 — human-readable documentation carried over from the
   * BSWMD-side `ContainerDef.desc` (the text body of `<DESC>`). The
   * skeleton carry-through is uniform for top containers, sub-containers,
   * and choice shells. `undefined` when the BSWMD omits `<DESC>` or
   * declares an empty `<DESC></DESC>`.
   */
  readonly description?: string;
}

export interface ArxmlReference {
  readonly kind: 'reference';
  readonly tagName: string;
  readonly shortName?: string;
  readonly value: string;
  /** AUTOSAR DEST attribute from <VALUE-REF DEST="..."> (e.g. "PDU", "COM-SIGNAL") */
  readonly dest?: string;
}

/**
 * v1.4.0 trust sprint — sub-sprint 17c.
 *
 * Catch-all variant for any element the parser does not classify as
 * module / container / reference (vendor extensions such as
 * `<SERVICE-NEEDS>`, `<EXCLUSIVE-AREA>`, `/EAS/`-namespaced elements).
 *
 * `parsed` is the **original fast-xml-parser node**, captured verbatim
 * during `classifyElement`. The serializer re-emits it via
 * `{ [tagName]: parsed }` without string re-parsing — `XMLBuilder`
 * accepts the same shape the parser produces (attributes under `@_`,
 * text under `#text`, child elements as object keys).
 *
 * Known limitation: sibling order between known and unknown elements
 * within the same parent is determined by model iteration order, not
 * original source order. Documented in CHANGELOG; full preservation
 * requires `preserveOrder: true`, deferred to v1.5+.
 */
export interface ArxmlUnknown {
  readonly kind: 'unknown';
  readonly tagName: string;
  /** Original fast-xml-parser node — passed verbatim to XMLBuilder for re-emit. */
  readonly parsed: Readonly<Record<string, unknown>>;
}

export type ParamValue =
  | { readonly type: 'string'; readonly value: string; readonly definitionRef?: string }
  | { readonly type: 'integer'; readonly value: number; readonly definitionRef?: string }
  | { readonly type: 'float'; readonly value: number; readonly definitionRef?: string }
  | { readonly type: 'boolean'; readonly value: boolean; readonly definitionRef?: string }
  | { readonly type: 'enum'; readonly value: string; readonly definitionRef?: string }
  | {
      readonly type: 'reference';
      readonly value: string;
      readonly dest?: string;
      readonly definitionRef?: string;
    };

/** Editor mode identifier (7 modes per F2). */
export type ParamEditMode =
  | 'string'
  | 'integer'
  | 'float'
  | 'boolean'
  | 'enum'
  | 'reference'
  | 'multiline';

export const SUPPORTED_ARXML_VERSIONS: readonly ArxmlVersion[] = [
  '4.2',
  '4.4',
  '4.6',
  '4.7',
  '5.0',
  // 5-digit literals — AUTOSAR standard form for R4.4+ releases:
  // 00046 = R4.6, 00048 = R19-11, 00049 = R20-11, 00050 = R21-11,
  // 00051 = R22-11.
  // 00047 (R4.7) intentionally omitted — no fixture proves vendor emission yet.
  '00046',
  '00048',
  '00049',
  '00050',
  '00051',
] as const;

/**
 * Result envelope used by all core API surfaces (parser, serializer, future validators).
 * Defined here (not in shared/) so that core/ stays self-contained and the
 * core → shared layer direction stays one-way. shared/types.ts re-exports this.
 */
export type Result<T, E = string> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly error: E };
