// AUTOSAR ARXML primitive types. All exported types are immutable data.
// Reference: AUTOSAR TPS_StandardizationTemplate (4.x).
//   https://www.autosar.org/fileadmin/standards/foundation/22-11/AUTOSAR_TPS_StandardizationTemplate.pdf

/**
 * v1.11.4 PATCH-A — single source of truth for ARXML versions that
 * have a 1:1 BSWMD mapping. `ArxmlVersion` (below) is the literal
 * union of this list, and `ARXML_VERSIONS` in version.ts derives the
 * BSWMD→ARXML 1:1 direct-map Set from the same source.
 *
 * `SUPPORTED_ARXML_VERSIONS` (below) is intentionally NOT derived
 * from this list — it is a hand-written subset that excludes 00005 /
 * 00006 (and 00047, which is also excluded from this canonical list).
 * See the `SUPPORTED_ARXML_VERSIONS` JSDoc for the parser-accept
 * rationale.
 *
 * v1.12.0 PATCH D4 (M1) — corrected the "reference-equal alias" claim,
 * which was inaccurate: `SUPPORTED_ARXML_VERSIONS` is hand-written.
 * Adding or removing a version here updates `ArxmlVersion` and the
 * direct-map Set automatically. To also add/remove it from the
 * parser-accept set, update `SUPPORTED_ARXML_VERSIONS` manually. The
 * pre-PATCH-A hand-synced pair (`SUPPORTED_ARXML_VERSIONS` +
 * `version.ts ARXML_VERSIONS`) drifted in v1.8.5 (commit 8870566)
 * when '4.0' was added to one but not the other, breaking R4.0 ECUC
 * file parsing; the regression tests in `__tests__/types.test.ts`
 * pin the subset invariant so the drift cannot recur.
 *
 * Keep entries in this order: dotted form first, then 5-digit literals.
 */
export const ARXML_DIRECT_MAP_VERSIONS = [
  '4.0',
  '4.2',
  '4.4',
  '4.6',
  '4.7',
  '5.0',
  // 5-digit literals — AUTOSAR standard form for R4.4+ releases:
  // 00046 = R4.6, 00048 = R19-11, 00049 = R20-11, 00050 = R21-11,
  // 00051 = R22-11.
  // 00047 (R4.7) intentionally omitted — no fixture proves vendor emission yet.
  '00005',
  '00006',
  '00046',
  '00048',
  '00049',
  '00050',
  '00051',
] as const;

export type ArxmlVersion = (typeof ARXML_DIRECT_MAP_VERSIONS)[number];

export interface ArxmlDocument {
  /** Root file path or logical name */
  readonly path: string;
  /** Detected AUTOSAR major version */
  readonly version: ArxmlVersion;
  /** Top-level <AR-PACKAGES> children */
  readonly packages: readonly ArxmlPackage[];
  /**
   * Sprint 14 — set when this document was generated by the BSWMD-to-ECUC
   * skeleton flow (Task 8 in plan). Used by `removeBswmdWithCascade`
   * to find dependents. Manual / Open ARXML flows leave this undefined.
   */
  readonly sourceBswmdPath?: string;
}

export interface ArxmlPackage {
  readonly shortName: string;
  readonly longName?: string;
  readonly path: string;
  readonly elements: readonly ArxmlElement[];
  /**
   * Nested AR-PACKAGES — recursive package hierarchy. Present only when the
   * package contains `<AR-PACKAGES>` children (e.g. R21/R22 BSWMD + EcucValues
   * with `AUTOSAR_R2x > EcucDefs > <module>` shape). Omitted for the flat
   * single-level shape so existing 5-fixture round-trip signatures stay
   * field-equal.
   */
  readonly packages?: readonly ArxmlPackage[];
  /**
   * v1.9.0 Sprint X — set on the top-level package produced by
   * `foldVendorPackages` when the collapse created a fresh wrapper
   * (i.e. the package didn't exist in the source doc, it was
   * synthesised by the fold). The Tree uses this marker to hoist
   * the contained module element past the vendor wrapper so users
   * see the ECUC module as the tree root, not the vendor
   * namespace. Source packages (untouched by fold) leave this
   * undefined; legacy single-layer packages (`/EcuC` wrapping an
   * `EcuC` module) leave this undefined; combined-mode file
   * wrappers leave this undefined. Only the fold-synthesised
   * top-level package carries the flag, so the hoisting decision
   * is unambiguous.
   */
  readonly isVendorFoldResult?: boolean;
}

export type ArxmlElement = ArxmlModule | ArxmlContainer | ArxmlReference | ArxmlUnknown;

export interface ArxmlModule {
  readonly kind: 'module';
  readonly tagName: string;
  readonly shortName: string;
  readonly params: Readonly<Record<string, ParamValue>>;
  readonly children: readonly ArxmlElement[];
  readonly references: readonly string[];
}

export interface ArxmlContainer {
  readonly kind: 'container';
  readonly tagName: string;
  readonly shortName: string;
  readonly params: Readonly<Record<string, ParamValue>>;
  readonly children: readonly ArxmlElement[];
  /**
   * v1.7.1 S1 — true when this shell came from a BSWMD choice container
   * (`<ECUC-CHOICE-ORIENTED-STRUCTURE-DEF>` / `<ECUC-CHOICE-CONTAINER-DEF>`)
   * rather than a plain sub-container (`<ECUC-PARAM-CONF-CONTAINER-DEF>`).
   * The UI uses this marker to render the "please pick a branch" prompt
   * instead of treating the shell as an editable plain container. Omitted
   * for plain sub-container shells (use `=== undefined`, not `=== false`).
   */
  readonly isChoiceContainer?: boolean;
  /**
   * v1.7.1 S1 — shortNames of the alternative branches the user can pick
   * from. Set only when `isChoiceContainer` is true; preserves iteration
   * order of `ContainerDef.choices` (which the BSWMD parser emits in
   * source order, so the UI picker renders branches in the same order).
   */
  readonly choiceBranches?: readonly string[];
  /**
   * v1.7.1 S3 — human-readable documentation carried over from the
   * BSWMD-side `ContainerDef.desc` (the text body of `<DESC>`). The
   * skeleton carry-through is uniform for top containers, sub-containers,
   * and choice shells. `undefined` when the BSWMD omits `<DESC>` or
   * declares an empty `<DESC></DESC>`.
   *
   * Note: declared with explicit `| undefined` for compatibility with
   * the project's `exactOptionalPropertyTypes: true` setting — the
   * skeleton writes `description: c.desc` where `c.desc` may be
   * `undefined`, which is rejected by strict-optional unless the
   * property type explicitly allows `undefined`.
   */
  readonly description?: string | undefined;
  /**
   * v1.9.0 Sprint X — BSWMD-side path stamped at construction time
   * (by `buildTopContainer` / `buildSubContainerShell` / `addContainer`).
   * The serializer renders it as a `<DEFINITION-REF DEST="ECUC-PARAM-CONF-CONTAINER-DEF">`
   * sibling of `<SHORT-NAME>` (or `ECUC-CHOICE-CONTAINER-DEF` when
   * `isChoiceContainer` is true). `undefined` when the container was
   * synthesized without a BSWMD definition (legacy in-memory docs that
   * pre-date the v1.9.0 stamping) — the serializer omits the
   * `<DEFINITION-REF>` child in that case so the field-equal round-trip
   * signature of pre-fix fixtures is preserved.
   *
   * Note: declared with explicit `| undefined` for compatibility with the
   * project's `exactOptionalPropertyTypes: true` setting — mirrors
   * `description` directly above.
   */
  readonly definitionRef?: string | undefined;
}

export interface ArxmlReference {
  readonly kind: 'reference';
  readonly tagName: string;
  readonly shortName?: string;
  readonly value: string;
  /** AUTOSAR DEST attribute from <VALUE-REF DEST="..."> (e.g. "PDU", "COM-SIGNAL") */
  readonly dest?: string;
}

/**
 * v1.4.0 trust sprint — sub-sprint 17c.
 *
 * Catch-all variant for any element the parser does not classify as
 * module / container / reference (vendor extensions such as
 * `<SERVICE-NEEDS>`, `<EXCLUSIVE-AREA>`, `/EAS/`-namespaced elements).
 *
 * `parsed` is the **original fast-xml-parser node**, captured verbatim
 * during `classifyElement`. The serializer re-emits it via
 * `{ [tagName]: parsed }` without string re-parsing — `XMLBuilder`
 * accepts the same shape the parser produces (attributes under `@_`,
 * text under `#text`, child elements as object keys).
 *
 * Known limitation: sibling order between known and unknown elements
 * within the same parent is determined by model iteration order, not
 * original source order. Documented in CHANGELOG; full preservation
 * requires `preserveOrder: true`, deferred to v1.5+.
 */
export interface ArxmlUnknown {
  readonly kind: 'unknown';
  readonly tagName: string;
  /** Original fast-xml-parser node — passed verbatim to XMLBuilder for re-emit. */
  readonly parsed: Readonly<Record<string, unknown>>;
}

export type ParamValue =
  | { readonly type: 'string'; readonly value: string; readonly definitionRef?: string }
  | { readonly type: 'integer'; readonly value: number; readonly definitionRef?: string }
  | { readonly type: 'float'; readonly value: number; readonly definitionRef?: string }
  | { readonly type: 'boolean'; readonly value: boolean; readonly definitionRef?: string }
  | { readonly type: 'enum'; readonly value: string; readonly definitionRef?: string }
  | {
      readonly type: 'reference';
      readonly value: string;
      readonly dest?: string;
      readonly definitionRef?: string;
    };

/** Editor mode identifier (7 modes per F2). */
export type ParamEditMode =
  | 'string'
  | 'integer'
  | 'float'
  | 'boolean'
  | 'enum'
  | 'reference'
  | 'multiline';

/**
 * v1.12.0 PATCH D4 (M1) — explicitly NOT derived from
 * `ARXML_DIRECT_MAP_VERSIONS`; it is a hand-written subset that
 * excludes 00005 / 00006 (and 00047, which is also excluded from the
 * canonical list above). This is the **parser-accept set**: ARXML
 * versions the parser will accept as input. It is a strict subset of
 * the 13-item direct-map set.
 *
 * Why exclude 00005 / 00006 from the parser-accept set: the parser
 * normalizes 5-digit r-form literals (`r4.0`, `r4.2`, ...) to dotted
 * form per AUTOSAR 4.x namespaces. The 00005 / 00006 5-digit literals
 * have no r-form equivalent in the AUTOSAR standard — R4.x maps to
 * 00046 (R4.6) onward. The BSWMD parser may still emit 00005 / 00006
 * (it accepts a wider input set), which is why version.ts keeps the
 * full 13-item set for the BSWMD→ARXML 1:1 direct-map.
 *
 * Adding a new version: add it to `ARXML_DIRECT_MAP_VERSIONS` (the
 * canonical list), then manually add it here if the parser should
 * accept it from real ECUC files. The regression test in
 * `__tests__/types.test.ts` pins the subset invariant.
 */
export const SUPPORTED_ARXML_VERSIONS: readonly ArxmlVersion[] = [
  '4.0',
  '4.2',
  '4.4',
  '4.6',
  '4.7',
  '5.0',
  // 5-digit literals — AUTOSAR standard form for R4.4+ releases:
  // 00046 = R4.6, 00048 = R19-11, 00049 = R20-11, 00050 = R21-11,
  // 00051 = R22-11.
  // 00005 / 00006 / 00047 (R4.7) intentionally omitted — see the
  // 00047 comment on ARXML_DIRECT_MAP_VERSIONS for the R4.7 reason,
  // and the SUPPORTED_ARXML_VERSIONS comment for the 00005/00006
  // reason.
  '00046',
  '00048',
  '00049',
  '00050',
  '00051',
];

/**
 * Result envelope used by all core API surfaces (parser, serializer, future validators).
 * Defined here (not in shared/) so that core/ stays self-contained and the
 * core → shared layer direction stays one-way. shared/types.ts re-exports this.
 */
export type Result<T, E = string> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly error: E };
