// Sprint 14 #1 — script engine types.
//
// Pure data shapes. No fs / no electron / no I/O. Safe to import from
// both main process and (in future) any code that needs the contract.

export type ScriptKind = 'validator' | 'transformer' | 'report' | 'free';

/** Single entry in the project's `scripts[]` array. */
export interface ScriptEntry {
  /** UUID v4 (generated by `script:save` IPC). */
  readonly id: string;

  /** UI display name. */
  readonly name: string;

  /** kebab-case, unique within project; used as the import target id. */
  readonly shortName: string;

  readonly kind: ScriptKind;

  /** Full JavaScript source. */
  readonly source: string;

  /** Static declaration of dependencies (for UI navigation; resolver re-scans source). */
  readonly imports: ReadonlyArray<{ readonly from: string; readonly names: readonly string[] }>;

  /** ISO timestamp. */
  readonly updatedAt: string;
}

/** Subset of ScriptEntry sent over IPC `script:list` (no source for size). */
export interface ScriptSummary {
  readonly id: string;
  readonly name: string;
  readonly shortName: string;
  readonly kind: ScriptKind;
  readonly updatedAt: string;
}

/** Single log line emitted by `ctx.log.*` during execution. */
export interface ScriptLog {
  readonly level: 'info' | 'warn' | 'error' | 'debug';
  readonly message: string;
  /** Unix ms. */
  readonly ts: number;
}

/** Single custom validation violation emitted by `ctx.validator.addViolation`. */
export interface ScriptViolation {
  /** MUST start with `script:` to avoid colliding with the 9 native kinds. */
  readonly kind: `script:${string}`;
  readonly severity: 'error' | 'warning';
  readonly containerPath?: string;
  readonly paramName?: string;
  readonly message: string;
  readonly data?: Readonly<Record<string, unknown>>;
}

/** Mutation applied to the project during a script run. */
export type ScriptMutation =
  | {
      readonly kind: 'set-param';
      readonly containerPath: string;
      readonly paramName: string;
      readonly newValue:
        | number
        | string
        | boolean
        | { readonly value: string; readonly dest?: string };
    }
  | { readonly kind: 'add-child'; readonly containerPath: string; readonly newShortName: string }
  | { readonly kind: 'remove-child'; readonly containerPath: string; readonly shortName: string };

/** Final result returned by `script:run`. */
export interface ScriptRunResult {
  readonly runId: string;
  readonly status: 'ok' | 'runtime-error' | 'timeout' | 'syntax-error' | 'import-error';
  readonly logs: ReadonlyArray<ScriptLog>;
  readonly violations: ReadonlyArray<ScriptViolation>;
  readonly mutations: ReadonlyArray<ScriptMutation>;
  /**
   * v1.20.0 T1 C2.4 — non-fatal step diagnostics surfaced by the
   * mutation engine (`applyPatchSteps`). Mirrors the wire-shape
   * `MutationStepWarning` in `src/shared/headless/ipc-contract.ts:287`
   * but is renderer-agnostic. Optional for backwards compatibility
   * with v1.19.x callers that pre-date the C2.4 rewrite.
   */
  readonly warnings?: ReadonlyArray<ScriptStepWarning>;
  readonly durationMs: number;
  readonly errorMessage?: string | undefined;
  readonly errorLine?: number | undefined;
  readonly errorColumn?: number | undefined;
}

/**
 * v1.20.0 T1 C2.4 — single non-fatal step diagnostic surfaced by
 * `applyPatchSteps`. Mirrors `MutationStepWarning` (the wire shape
 * from `src/shared/headless/ipc-contract.ts`) but is defined in the
 * script-types module so the renderer can type-narrow without
 * pulling in the headless IPC contract.
 *
 * The `kind` discriminator is intentionally a `string` (not a
 * literal union) so future diagnostic kinds (e.g. `variant-downgrade`,
 * `type-coercion`) can be added without forcing renderer callers
 * to widen the type.
 */
export interface ScriptStepWarning {
  readonly stepIndex: number;
  readonly kind: string;
  readonly message: string;
}

/**
 * Type snapshot exposed via ScriptParam.type. The vm-runner uses this
 * for runtime type-guard on `setValue` writes; the actual full
 * `ParamValue` lives in `src/core/arxml/types.ts` (with `type` + `value`).
 *
 * Kept narrow here on purpose — the script ctx is intentionally
 * view-oriented and does not surface the AUTOSAR definitionRef
 * metadata to user scripts.
 */
export type ParamSnapshot = {
  readonly type: 'integer' | 'float' | 'boolean' | 'string' | 'enum' | 'reference' | 'multiline';
  readonly containerPath: string;
};

/** Shape of a parameter `value` as user scripts see it. */
export type ParamValue =
  | number
  | string
  | boolean
  | { readonly value: string; readonly dest?: string };
