// tests/round-trip/tolerance-rules.ts
// Explicit whitelist for round-trip diffs (Q5 B — v1.5.1 spec).
//
// Diffs in these categories are allowed and don't fail the round-trip tests.
// Every unlisted difference IS a real regression (dropped element, reordered
// top-level children, lost DEFINITION-REF path, etc.).
//
// Why a whitelist and not a blacklist:
//   - Whitelist keeps the contract auditable: a reviewer can read these
//     lines and know exactly which variations are tolerated.
//   - A new serializer improvement that introduces a NEW tolerance category
//     (e.g. entity encoding normalization) requires touching this file —
//     forcing an explicit decision instead of silently widening the net.
//
// Categories:
//   1. namespacePrefixOrder: `xmlns="..."` and `xmlns:foo="..."` declaration
//      order can vary; namespace prefix *declarations* themselves are
//      preserved as long as they cover the same URIs.
//   2. namespaceSchemaLocation: `xsi:schemaLocation` value is regenerated by
//      the serializer from its internal version table (see
//      `serializer.ts:buildSchemaLocation`). Source files from EB tresos
//      and Vector use 5-digit xsd names + `r4.0` namespace URIs; the
//      serializer's table keys on the detected version. A file that
//      declares `xmlns="r4.0"` but `xsi:schemaLocation=".../r4.2 AUTOSAR_4-2-2.xsd"`
//      (a vendor quirk) will round-trip with a normalized namespace URL.
//      This is tolerated because the XSD name — the authoritative version
//      hint — is preserved; the URL is purely cosmetic.
//   3. whitespace: CRLF vs LF, indentation, blank lines (XML round-trip never
//      preserves whitespace exactly because fast-xml-parser reformats it)
//   4. comments: comment text and position between elements (the v1.5.1
//      parser does not model comments in NormalizedDocument — comment
//      preservation is a v1.6.0+ concern)
//   5. attributeOrder: attribute order within an opening tag (XML attributes
//      are semantically unordered; round-trip doesn't preserve declaration
//      order)

export const TOLERANCE_RULES = {
  namespacePrefixOrder: true,
  namespaceSchemaLocation: true,
  whitespace: true,
  comments: true,
  attributeOrder: true,
} as const;
