// v1.25.0 T4 — Real-OEM 75-row ship-blocking regression test for the
// full T1-T3 pipeline.
//
// Per the [real-oem-fixture-required-for-vendor-format-work] PKM
// permanent note and the v1.22.0 / v1.23.0 / v1.24.0 precedent,
// hand-crafted fixtures are insufficient for vendor-format parsers
// (xlsx/ecuc). This file is the SHIP-BLOCKING invariant the v1.25.0
// spec §Risks requires: a full Vector DBC-derived 75-row .xlsx (30
// ComIPdu + 30 ComSignal + 5 CanIfTxPdu + 5 CanIfRxPdu + 5
// PduRRoutingPath) exercises the entire template → parse → commit
// round-trip. If this test fails, the implementation is wrong — fix
// the implementation, not the test.
//
// The committed 75-row `.xlsx` lives at
// `samples/comstack-existing-fixture.xlsx` (built deterministically
// by `scripts/build-comstack-fixture.mjs`). The supporting fixture
// project (3 BSWMDs + 3 empty Com-stack ARXMLs + manifest) lives at
// `samples/comstack-existing-fixture/`. The T4 fixture EXTENDS the
// demo project's BSWMDs — the bare demo BSWMDs only declared
// ComIPdu + empty PduRRoutingPath + CanIfInitCfg (no CanIfTxPdu /
// CanIfRxPdu / ComSignal), so the T1-T3 pipeline couldn't be
// exercised end-to-end against them.
//
// The test copies the fixture project into a fresh tmp dir each
// case so the test is hermetic (never mutates the on-disk samples).
// Per the spec §Risks the FIXTURE itself is the SoT — once committed
// it must not be regenerated by CI; only `scripts/build-comstack-fixture.mjs`
// (developer hand-run) can rewrite it.

import { copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import {
  setOpenProjectManifestPath,
  __resetOpenProjectManifestPathForTests,
} from '../project-manifest-state.js';
import { xlsxEcucBatchImportHandler } from '../xlsxEcucBatchImportHandler.js';
import { xlsxEcucBatchParseHandler } from '../xlsxEcucBatchParseHandler.js';
import { xlsxEcucBatchWriteBatchTemplateHandler } from '../xlsxEcucBatchTemplateHandler.js';

const FIXTURE_DIR = join(process.cwd(), 'samples/comstack-existing-fixture');
const FIXTURE_XLSX = join(process.cwd(), 'samples/comstack-existing-fixture.xlsx');

// ---------------------------------------------------------------------------
// Fixture — copy committed BSWMDs + empty Com-stack ARXMLs + manifest into
// a fresh tmp dir so the case is hermetic. The brief's protocol: "Never
// mutate the on-disk fixture samples".
// ---------------------------------------------------------------------------

interface SeededFixture {
  readonly workDir: string;
  readonly manifestPath: string;
  readonly comPath: string;
  readonly canIfPath: string;
  readonly pduRPath: string;
  readonly comBswmdPath: string;
  readonly canIfBswmdPath: string;
  readonly pduRBswmdPath: string;
}

function seedFixture(): SeededFixture {
  const workDir = mkdtempSync(join(tmpdir(), 'claude-autosarcfg-v125-t4-real-'));
  copyFileSync(join(FIXTURE_DIR, 'Com.bswmd.arxml'), join(workDir, 'Com.bswmd.arxml'));
  copyFileSync(join(FIXTURE_DIR, 'CanIf.bswmd.arxml'), join(workDir, 'CanIf.bswmd.arxml'));
  copyFileSync(join(FIXTURE_DIR, 'PduR.bswmd.arxml'), join(workDir, 'PduR.bswmd.arxml'));
  copyFileSync(join(FIXTURE_DIR, 'Com_Config.arxml'), join(workDir, 'Com_Config.arxml'));
  copyFileSync(join(FIXTURE_DIR, 'CanIf_Config.arxml'), join(workDir, 'CanIf_Config.arxml'));
  copyFileSync(join(FIXTURE_DIR, 'PduR_Config.arxml'), join(workDir, 'PduR_Config.arxml'));
  const manifestText = readFileSync(join(FIXTURE_DIR, 'demo.autosarcfg.json'), 'utf-8');
  const manifestPath = join(workDir, 'demo.autosarcfg.json');
  writeFileSync(manifestPath, manifestText, 'utf-8');
  setOpenProjectManifestPath(manifestPath);
  return {
    workDir,
    manifestPath,
    comPath: join(workDir, 'Com_Config.arxml'),
    canIfPath: join(workDir, 'CanIf_Config.arxml'),
    pduRPath: join(workDir, 'PduR_Config.arxml'),
    comBswmdPath: join(workDir, 'Com.bswmd.arxml'),
    canIfBswmdPath: join(workDir, 'CanIf.bswmd.arxml'),
    pduRBswmdPath: join(workDir, 'PduR.bswmd.arxml'),
  };
}

function cleanup(workDir: string): void {
  rmSync(workDir, { recursive: true, force: true });
}

afterEach(() => {
  __resetOpenProjectManifestPathForTests();
});

// ---------------------------------------------------------------------------
// 1. 75-row pipeline — template download → user upload → commit yields
//    75 new containers (30 ComIPdu + 30 ComSignal + 5 CanIfTxPdu + 5
//    CanIfRxPdu + 5 PduRRoutingPath).
// ---------------------------------------------------------------------------

describe('xlsxEcucBatchImportHandler (v1.25.0 T4 — real-OEM 75-row)', () => {
  it('75-row pipeline: template download → upload → commit yields 75 new containers', async () => {
    const fx = seedFixture();
    try {
      // 1. Template generation — proves T3's BSWMD-derived emission
      //    works on the fixture project's 5 kinds × ≥3 params each.
      const tmpl = await xlsxEcucBatchWriteBatchTemplateHandler({
        projectManifestPath: fx.manifestPath,
      });
      expect(tmpl.ok).toBe(true);
      if (!tmpl.ok) return;

      // 2. User upload — read the committed fixture .xlsx and parse
      //    via the T2 handler. The parse handler must surface exactly
      //    75 instances and 0 collisions (the fixture starts with
      //    empty Com-stack ARXMLs).
      const xlsxBytes = new Uint8Array(readFileSync(FIXTURE_XLSX));
      const parsed = await xlsxEcucBatchParseHandler({
        projectManifestPath: fx.manifestPath,
        xlsxBytes,
      });
      expect(parsed.ok).toBe(true);
      if (!parsed.ok) return;
      expect(parsed.value.instances.length).toBe(75);
      expect(Object.keys(parsed.value.collisions)).toHaveLength(0);

      // 3. Commit — apply patches + atomic 3-file write.
      // The T2 import handler treats `resolutions` entries as
      // `'overwrite' | 'skip'`; absent keys default to **skip**
      // (line 322 of xlsxEcucBatchImportHandler.ts). For a
      // first-touch project (no pre-existing instances), every row
      // needs an explicit `'overwrite'` resolution to land; the
      // heuristic-collision map is empty here.
      const overwriteAll: Record<string, 'overwrite'> = {};
      for (const inst of parsed.value.instances) {
        overwriteAll[`${inst.sheet}:${inst.shortName}`] = 'overwrite';
      }
      const commit = await xlsxEcucBatchImportHandler({
        projectManifestPath: fx.manifestPath,
        instances: parsed.value.instances,
        resolutions: overwriteAll,
      });
      expect(commit.ok).toBe(true);
      if (!commit.ok) {
        // Surface the failure message in test output for diagnosis.
        // eslint-disable-next-line no-console
        console.error('commit failed:', commit.error);
        return;
      }
      expect(commit.value.added).toBeGreaterThanOrEqual(75);
      expect(commit.value.overwritten).toBe(75);
      expect(commit.value.skipped).toBe(0);
      // 30 ComIPdu + 30 ComSignal → Com file
      expect(commit.value.perFile.Com).toBeGreaterThanOrEqual(60);
      // 5 CanIfTxPdu + 5 CanIfRxPdu → CanIf file
      expect(commit.value.perFile.CanIf).toBeGreaterThanOrEqual(10);
      // 5 PduRRoutingPath → PduR file
      expect(commit.value.perFile.PduR).toBeGreaterThanOrEqual(5);

      // The 3 Com-stack files on disk must have been rewritten and
      // contain the first row's SHORT-NAME (anchor for the pinned
      // regression assertion below).
      const comText = readFileSync(fx.comPath, 'utf-8');
      const canIfText = readFileSync(fx.canIfPath, 'utf-8');
      const pduRText = readFileSync(fx.pduRPath, 'utf-8');
      expect(comText).toContain('Pdu_Engine_Speed');
      expect(comText).toContain('Sig_Engine_RPM');
      expect(canIfText).toContain('TxPdu_Engine_ECM');
      expect(canIfText).toContain('RxPdu_Engine_ECM');
      expect(pduRText).toContain('RtePath_ComPdu_CanIfTxPdu');
    } finally {
      cleanup(fx.workDir);
    }
  }, 60_000);

  // -------------------------------------------------------------------------
  // 2. Pinned regression — pin concrete SHORT-NAME presence under the
  //    correct ECUC parent + concrete cell values for the textual/enum
  //    params (which reliably land through the T1-T3 pipeline). Numeric
  //    param VALUES are intentionally NOT pinned here — see `Concerns`
  //    in the T4 report for the latent applySetParam-integer
  //    no-op. The point of this case is to anchor "the SHORT-NAME
  //    landed, the textual/enum params landed, and the ECUC parent
  //    path resolved" — not to re-litigate applySetParam semantics.
  //
  //    Pins per kind:
  //      - ComIPdu → Pdu_Engine_Speed (first row) ⇒ ComIPduDirection=SEND
  //      - CanIfTxPdu → TxPdu_Engine_ECM (first row)
  //      - PduRRoutingPath → RtePath_ComPdu_CanIfTxPdu (first row)
  //
  //    A regression that drops any of them surfaces immediately here
  //    per the brief §Risks mandate.
  // -------------------------------------------------------------------------

  it('pinned regression: pinned SHORT-NAMEs land under correct ECUC parents with textual-param values', async () => {
    const fx = seedFixture();
    try {
      const tmpl = await xlsxEcucBatchWriteBatchTemplateHandler({
        projectManifestPath: fx.manifestPath,
      });
      expect(tmpl.ok).toBe(true);
      if (!tmpl.ok) return;

      const xlsxBytes = new Uint8Array(readFileSync(FIXTURE_XLSX));
      const parsed = await xlsxEcucBatchParseHandler({
        projectManifestPath: fx.manifestPath,
        xlsxBytes,
      });
      expect(parsed.ok).toBe(true);
      if (!parsed.ok) return;

      const overwriteAll: Record<string, 'overwrite'> = {};
      for (const inst of parsed.value.instances) {
        overwriteAll[`${inst.sheet}:${inst.shortName}`] = 'overwrite';
      }
      const commit = await xlsxEcucBatchImportHandler({
        projectManifestPath: fx.manifestPath,
        instances: parsed.value.instances,
        resolutions: overwriteAll,
      });
      expect(commit.ok).toBe(true);
      if (!commit.ok) return;

      const comText = readFileSync(fx.comPath, 'utf-8');
      const canIfText = readFileSync(fx.canIfPath, 'utf-8');
      const pduRText = readFileSync(fx.pduRPath, 'utf-8');

      // Pin #1: ComIPdu → Pdu_Engine_Speed lands under
      // Com/ComConfig/ComIPdu with ComIPduDirection=SEND textual
      // value (a non-default enum literal from the BSWMD).
      expect(comText).toContain('<SHORT-NAME>Pdu_Engine_Speed</SHORT-NAME>');
      const comTempBlock = comText.match(
        /<SHORT-NAME>Pdu_Engine_Speed<\/SHORT-NAME>([\s\S]*?)<\/ECUC-CONTAINER-VALUE>/,
      );
      expect(comTempBlock).not.toBeNull();
      if (comTempBlock !== null) {
        // Com IPdu parent path correctly resolved to BSWMD-side def.
        expect(comTempBlock[0]).toContain(
          '<DEFINITION-REF DEST="ECUC-PARAM-CONF-CONTAINER-DEF">/AUTOSAR/Com/ComConfig/ComIPdu</DEFINITION-REF>',
        );
        // ComIPduDirection=SEND textual (non-default enum literal).
        expect(comTempBlock[0]).toContain('<VALUE>SEND</VALUE>');
      }

      // Pin #2: CanIfTxPdu → TxPdu_Engine_ECM lands under
      // CanIf/CanIfConfig/CanIfTxPdu. The first row's DLC param is
      // 8 (from the .xlsx builder, idx=0 → CanIfTxPduDlc=8).
      expect(canIfText).toContain('<SHORT-NAME>TxPdu_Engine_ECM</SHORT-NAME>');
      const txPduBlock = canIfText.match(
        /<SHORT-NAME>TxPdu_Engine_ECM<\/SHORT-NAME>([\s\S]*?)<\/ECUC-CONTAINER-VALUE>/,
      );
      expect(txPduBlock).not.toBeNull();
      if (txPduBlock !== null) {
        expect(txPduBlock[0]).toContain(
          '<DEFINITION-REF DEST="ECUC-PARAM-CONF-CONTAINER-DEF">/AUTOSAR/CanIf/CanIfConfig/CanIfTxPdu</DEFINITION-REF>',
        );
      }

      // Pin #3: PduRRoutingPath → RtePath_ComPdu_CanIfTxPdu lands
      // under PduR/PduRRoutingPaths/PduRRoutingPath.
      expect(pduRText).toContain('<SHORT-NAME>RtePath_ComPdu_CanIfTxPdu</SHORT-NAME>');
      const rteBlock = pduRText.match(
        /<SHORT-NAME>RtePath_ComPdu_CanIfTxPdu<\/SHORT-NAME>([\s\S]*?)<\/ECUC-CONTAINER-VALUE>/,
      );
      expect(rteBlock).not.toBeNull();
      if (rteBlock !== null) {
        expect(rteBlock[0]).toContain(
          '<DEFINITION-REF DEST="ECUC-PARAM-CONF-CONTAINER-DEF">/AUTOSAR/PduR/PduRRoutingPaths/PduRRoutingPath</DEFINITION-REF>',
        );
      }
    } finally {
      cleanup(fx.workDir);
    }
  }, 60_000);

  // -------------------------------------------------------------------------
  // 3. v1.25.x PATCH T2 regression — ComPduId integer default lands as
  //    `<VALUE>1</VALUE>` through the FULL import handler (template →
  //    parse → commit). Pins the integer-default surface that T4 review
  //    misdiagnosed as a latent `applySetParam` no-op. The diagnostic in
  //    `src/core/__tests__/c1-integer-default-diagnostic.test.ts`
  //    confirmed the engine + serializer pipeline correctly lands
  //    integer values that differ from BSWMD defaults; this case pins
  //    the same invariant at the IPC handler integration boundary.
  //
  //    Per the v1.25.0 errata (docs/release-notes/v1.25.0/errata.md),
  //    the original "latent bug" attribution was disproved by the T2
  //    diagnostic. This test stays as a regression guard for any future
  //    change to the engine or serializer that re-introduces an
  //    integer-default no-op.
  // -------------------------------------------------------------------------

  it('ComPduId=1 integer lands as <VALUE>1</VALUE> in committed ARXML (T2 integer-default regression)', async () => {
    const fx = seedFixture();
    try {
      // Build a single-row `.xlsx` programmatically with ComIPdu
      // Pdu_Engine_Speed carrying ComPduId=1. Re-uses the existing
      // template + parse pipeline so the path through the import
      // handler is identical to production.
      const tmpl = await xlsxEcucBatchWriteBatchTemplateHandler({
        projectManifestPath: fx.manifestPath,
      });
      expect(tmpl.ok).toBe(true);
      if (!tmpl.ok) return;

      const parsed = await xlsxEcucBatchParseHandler({
        projectManifestPath: fx.manifestPath,
        xlsxBytes: new Uint8Array(readFileSync(FIXTURE_XLSX)),
      });
      expect(parsed.ok).toBe(true);
      if (!parsed.ok) return;

      // Locate the first ComIPdu row and override its ComPduId to 1.
      // The fixture declares ComPduId with DEFAULT-VALUE=0, so a
      // value of 1 differs from the default and exercises the
      // integer-default surface end-to-end.
      const instances = parsed.value.instances.map((row) =>
        row.sheet === 'ComIPdu' && row.shortName === 'Pdu_Engine_Speed'
          ? { ...row, params: { ...row.params, ComPduId: 1 } }
          : row,
      );

      const overwriteAll: Record<string, 'overwrite'> = {};
      for (const inst of instances) {
        overwriteAll[`${inst.sheet}:${inst.shortName}`] = 'overwrite';
      }
      const commit = await xlsxEcucBatchImportHandler({
        projectManifestPath: fx.manifestPath,
        instances,
        resolutions: overwriteAll,
      });
      expect(commit.ok).toBe(true);
      if (!commit.ok) return;

      // Pin the integer-default surface: Pdu_Engine_Speed's
      // <PARAMETER-VALUES> block must contain <VALUE>1</VALUE> for
      // the ComPduId param, not the BSWMD <DEFAULT-VALUE>0</DEFAULT-VALUE>.
      const comText = readFileSync(fx.comPath, 'utf-8');
      const pduBlock = comText.match(
        /<SHORT-NAME>Pdu_Engine_Speed<\/SHORT-NAME>([\s\S]*?)<\/ECUC-CONTAINER-VALUE>/,
      );
      expect(pduBlock).not.toBeNull();
      if (pduBlock !== null) {
        expect(pduBlock[0]).toMatch(
          /<DEFINITION-REF DEST="ECUC-INTEGER-PARAM-DEF">[^<]*ComPduId<\/DEFINITION-REF>\s*<VALUE>1<\/VALUE>/,
        );
      }
    } finally {
      cleanup(fx.workDir);
    }
  }, 60_000);
});
